<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions targetNamespace="http://VirtualCollaboration" xmlns:apachesoap="http://xml.apache.org/xml-soap" xmlns:impl="http://VirtualCollaboration" xmlns:intf="http://VirtualCollaboration" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
<!--WSDL created by Apache Axis version: 1.4
Built on Apr 22, 2006 (06:55:48 PDT)-->
 <wsdl:types>
  <schema elementFormDefault="qualified" targetNamespace="http://VirtualCollaboration" xmlns="http://www.w3.org/2001/XMLSchema">
   <element name="seeAnnouncements">
    <complexType>
     <sequence>
      <element name="groupID" type="xsd:int"/>
     </sequence>
    </complexType>
   </element>
   <element name="seeAnnouncementsResponse">
    <complexType/>
   </element>
  </schema>
 </wsdl:types>

   <wsdl:message name="seeAnnouncementsResponse">

      <wsdl:part element="impl:seeAnnouncementsResponse" name="parameters">

      </wsdl:part>

   </wsdl:message>

   <wsdl:message name="seeAnnouncementsRequest">

      <wsdl:part element="impl:seeAnnouncements" name="parameters">

      </wsdl:part>

   </wsdl:message>

   <wsdl:portType name="Announcement">

      <wsdl:operation name="seeAnnouncements">

         <wsdl:input message="impl:seeAnnouncementsRequest" name="seeAnnouncementsRequest">

       </wsdl:input>

         <wsdl:output message="impl:seeAnnouncementsResponse" name="seeAnnouncementsResponse">

       </wsdl:output>

      </wsdl:operation>

   </wsdl:portType>

   <wsdl:binding name="AnnouncementSoapBinding" type="impl:Announcement">

      <wsdlsoap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>

      <wsdl:operation name="seeAnnouncements">

         <wsdlsoap:operation soapAction=""/>

         <wsdl:input name="seeAnnouncementsRequest">

            <wsdlsoap:body use="literal"/>

         </wsdl:input>

         <wsdl:output name="seeAnnouncementsResponse">

            <wsdlsoap:body use="literal"/>

         </wsdl:output>

      </wsdl:operation>

   </wsdl:binding>

   <wsdl:service name="AnnouncementService">

      <wsdl:port binding="impl:AnnouncementSoapBinding" name="Announcement">

         <wsdlsoap:address location="http://localhost:8080/Virtual_Collaboration/services/Announcement"/>

      </wsdl:port>

   </wsdl:service>

</wsdl:definitions>
